---

- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"
  tags: install

- name: GIT | clone brewmaster-frontend repository
  git:
    repo: "{{ frontend_repo['url'] }}"
    version: "{{ frontend_repo['version'] | default(omit) }}"
    dest: "{{ frontend_repo['dest'] }}"
    force: true
  tags: install

- name: NPM | install
  npm:
    path: "{{ frontend_repo['dest'] }}"
  tags: install

- name: SYSTEMD | nodejs repo absolute path
  command: "pwd"
  args:
    chdir: "{{ frontend_repo['dest'] }}"
  register: repo_absolute_path
  changed_when: false

- name: SYSTEMD | copy unit file
  become: true
  template:
    src: "nodejs_unit_file.service.j2"
    dest: "/etc/systemd/system/{{ frontend_service['name'] }}.service"
  register: unit_file
  notify: SYSTEMD | frontend restart
  tags: configure

- name: SYSTEMD | start frontend
  become: true
  when: unit_file.changed
  systemd:
    daemon_reload: true
    name: "{{ frontend_service['name'] }}"
    state: started
    enabled: true
  tags: configure
